# Generated by Django 4.0.3 on 2022-03-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_aptekalar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aptekalar',
            old_name='title',
            new_name='name',
        ),
    ]
