# Generated by Django 4.0.3 on 2022-03-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_sotuvchilar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('available', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(default='Tashkent', max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('Sotuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.sotuvchilar')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_ended', models.DateTimeField(auto_now_add=True)),
                ('Dorilar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.dorilar')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.order')),
            ],
        ),
    ]
