# Generated by Django 4.0.3 on 2022-03-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_dorilar_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Sotuvchi',
            new_name='sotuvchi',
        ),
    ]
