# Generated by Django 4.0.3 on 2022-03-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_rename_sotuvchi_order_sotuvchi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Dorilar',
            new_name='dorilar',
        ),
    ]
