# Generated by Django 4.0.3 on 2022-03-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_rename_dorilar_orderitem_dorilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='apteka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.aptekalar'),
        ),
    ]
