# Generated by Django 4.0.3 on 2022-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_orderitem_apteka'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptekalar',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
