# Generated by Django 4.0.3 on 2022-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0010_aptekalar_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptekalar',
            name='description',
            field=models.TextField(),
        ),
    ]
