# Generated by Django 4.0.3 on 2022-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0012_orderqarz'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqarz',
            name='qoldi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
