# Generated by Django 4.0.3 on 2022-03-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0014_orderqarzitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderqarzitem',
            old_name='date_ended',
            new_name='bought_day',
        ),
    ]
