# Generated by Django 4.0.3 on 2022-03-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0015_rename_date_ended_orderqarzitem_bought_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderqarzitem',
            old_name='order',
            new_name='orderQarz',
        ),
    ]
