# Generated by Django 4.0.3 on 2022-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0016_rename_order_orderqarzitem_orderqarz'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqarzitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
