# Generated by Django 4.0.3 on 2022-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0017_orderqarzitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqarzitem',
            name='qoldi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderqarzitem',
            name='umumiy_summa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
