# Generated by Django 4.0.3 on 2022-03-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0019_orderqarzitem_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqarzitem',
            name='apteka_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderqarzitem',
            name='dori_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
