# Generated by Django 4.0.3 on 2022-03-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0021_orderqarzitem_day_orderqarzitem_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderqarzitem',
            name='day',
        ),
        migrations.RemoveField(
            model_name='orderqarzitem',
            name='month',
        ),
        migrations.RemoveField(
            model_name='orderqarzitem',
            name='year',
        ),
    ]
