# Generated by Django 4.0.3 on 2022-03-23 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0022_remove_orderqarzitem_day_remove_orderqarzitem_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqarzitem',
            name='bought_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
