# Generated by Django 4.0.3 on 2022-03-25 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0028_alter_orderqarzitem_bought_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqarz',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
