# Generated by Django 4.0.3 on 2022-03-30 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0035_remove_sotuvchilar_user_sotuvchilar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotuvchilar',
            name='user',
        ),
        migrations.AddField(
            model_name='sotuvchilar',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
