# Generated by Django 4.0.3 on 2022-03-30 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0036_remove_sotuvchilar_user_sotuvchilar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptekalar',
            name='user',
        ),
        migrations.AddField(
            model_name='aptekalar',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
