# Generated by Django 4.0.3 on 2022-03-30 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0037_remove_aptekalar_user_aptekalar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptekalar',
            name='user',
        ),
        migrations.AddField(
            model_name='aptekalar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
