# Generated by Django 4.0.3 on 2022-06-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0039_alter_aptekalar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqarz',
            name='date',
            field=models.DateField(),
        ),
    ]
